name: ShopTop
version: ${project.version}
main: com.twojapakiet.shoptop.ShopTop
api-version: '1.21'
load: POSTWORLD
author: TwojaNazwa
softdepend: [EconomyShopGUI, EconomyShopGUI-Premium, PlaceholderAPI]
