name: ShopTop
version: ${project.version}
main: com.twojapakiet.shoptop.ShopTop
api-version: '1.21'
author: TwojaNazwa
# WAŻNE: depend wymusza ładowanie PO tych pluginach
depend: [PlaceholderAPI]
softdepend: [EconomyShopGUI, EconomyShopGUI-Premium]
