name: ShopTop
version: ${project.version}
main: com.twojapakiet.shoptop.ShopTop
api-version: '1.21'
load: POSTWORLD
author: TwojaNazwa
softdepend: [EconomyShopGUI-Premium, PlaceholderAPI]


commands:
  shoptop:
    description: Główna komenda pluginu ShopTop
    aliases: [st]
    permission: shoptop.admin
    usage: /<command> reload
